### ISSUE TITLE
How to get intersection point of particular texture?

### ISSUE THREAD

**Issue by chirag-aura** [pmndrs/react-xr#106]
I am implementing one project of art gallery in that I need to move around in gallery using ray intersection at floor.

when my raycast is on floor and select event call than I need to change position of player. but I don't know how to get that point of intersection. 

if anyone know please help me.

**Comment by JenniferFalkenstein** [comment]
Hi there 😄 I have the same issue right now. Since you closed this issue, did you find a solution?
