### ISSUE TITLE
react-three-gui compatibility

### ISSUE THREAD

**Issue by checksummaster** [pmndrs/react-xr#12]
If I use an app that use react-three-gui and I'm not in VR, I see the menu (or react-three-gui) but control seems not added.
Example:
`<ControlsProvider><Canvas>...</Canvas><Controls /></ControlsProvider> Work but
<ControlsProvider><VRCanvas>...</VRCanvas><Controls /></ControlsProvider> not work`

Note: I understand that in VR (after pressing the button), we can't use react-three-gui then I understand that for VR it may be a minor issue.

to patch my app, I do something like that but it not clean.

`function Canvas2({ children, ...rest }) {
  var vr = true; // in really VR come from a parameters of the URL (HTTP://app?vr=true/false)
  return vr?<VRCanvas>{children}</VRCanvas>:<ControlsProvider><Canvas>{children}</Canvas><Controls /></ControlsProvider>
}
`

**Comment by sniok** [comment]
hi, I checked out example codesandbox from 'react-three-gui' repo and tried to replace Canvas with VRCanvas and could replicate the bug. after a couple of minutes with debugger it seems like a problem with context in react-three-gui. there are also other people experiencing the same problem with custom canvas wrappers in this issue https://github.com/birkir/react-three-gui/issues/23

**Comment by sniok** [comment]
it seems like a limitation of react-three-fiber https://github.com/pmndrs/react-three-fiber/issues/43

**Comment by checksummaster** [comment]
As I see it should be fixe in react-three-gui... Thanks
