### ISSUE TITLE
Forcing the user out of VR mode?

### ISSUE THREAD

**Issue by tomw13** [pmndrs/react-xr#123]
We are making a VR-based game that redirects to a results page (not in VR) on game end. When this happens while the user is in a VR session using WebXR though, the screen goes black and the redirect fails. Is there any way to force the user out of the VR session itself?

**Comment by CodyJasonBennett** [comment]
Threejs lightly abstracts the WebXR API, so you can use native methods there:
 - https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Startup_and_shutdown#ending_the_webxr_session

```js
import { useThree } from '@react-three/fiber'

const { gl } = useThree()

// end session
const session = gl.xr.getSession()
await session.end()
```

**Comment by tomw13** [comment]
Thank you so much, we have it fully working now!
