### ISSUE TITLE
useXR().player - what does it represent when not in VR Mode

### ISSUE THREAD

**Issue by panigrah** [pmndrs/react-xr#124]
when I am not in VR mode, I can get the "player" by calling useXR. 
What does player represent when not in VR mode? 

Specifically I want to move the player using the keyboard when not in VR mode using player.position.

**Comment by CodyJasonBennett** [comment]
Player is a group which the camera is parented under:

```js
<player>
  <state.camera />
</player>
```

So moving the player will move the camera in any case.

**Comment by chillbert** [comment]
@CodyJasonBennett so how do I access the camera (or the player = headset = camera) in VR/AR mode? 

```
const { player } = useXR();
return <Text color={"red"}>{JSON.stringify(player.position)}</Text>
```

this stays 0,0,0

**Comment by CodyJasonBennett** [comment]
No hook should be causing immutable updates every frame. You should be polling for position from pose.

```jsx
const { player } = useXR();
const textRef = useRef()

useFrame(() => {
  textRef.current.text = JSON.stringify(player.position)
})

return <Text ref={textRef} color={'red'} />
```

**Comment by chillbert** [comment]
@CodyJasonBennett text stays {x:0,y:0,z:0}...

```
  useFrame((state, delta) =>{
        if(textRef&& textRef.current){
      textRef.current.text = JSON.stringify(player.position)
      textRef.current.color = "green";
     }
})
```

the text gets green, but stays 0... I am using meta Quest 2.

**Comment by CodyJasonBennett** [comment]
Needs to set `textRef.current._needsSync = true` at the end of the pass. If you need further help, please ask in our Discord https://discord.gg/poimandres. You should avoid commenting on old issues since close to 90% of the time they will not be seen.

**Comment by chillbert** [comment]
@CodyJasonBennett _needsSync doesn't change anything...
I see your point because of the closed issue - but it will still get crawled and people with similar issues will hopefully find this post.
player.position is 0.. I tested it now also with an android phone in VR/AR mode and remote debugging over chrome inspector:

```
  useFrame((state, delta) =>{
    console.log("player",player.position);
});

```
_`player _Vector3 {x: 0, y: 0, z: 0}`_

**Comment by Zaniyar** [comment]
for anyone trying to access the users/headsets/cameras position in VR/AR: there is actually a perspective camera as a child object in the player group. Just console.log(player) to see it. 

So what you want is: 

```
const {player} = useXR();
const position = player.children[0].position;
```
