### ISSUE TITLE
How to exit VR from programmatically?

### ISSUE THREAD

**Issue by panigrah** [pmndrs/react-xr#125]

**Comment by CodyJasonBennett** [comment]
See #123.

> Threejs lightly abstracts the WebXR API, so you can use native methods there:
>  - https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Startup_and_shutdown#ending_the_webxr_session
> 
> ```js
> import { useThree } from '@react-three/fiber'
> 
> const { gl } = useThree()
> 
> // end session
> const session = gl.xr.getSession()
> await session.end()
> ```
