### ISSUE TITLE
Background scene got faded(color contrast) after change <Canvas> to <VRCanvas>

### ISSUE THREAD

**Issue by chanawee-jan** [pmndrs/react-xr#14]
Hello,

I am using react-three-fiber with three. And, I want to make my web with 360 panoramic background can be opened by VR by changing from `<Canvas>` to `<VRCanvas> `

```
import { Canvas} from 'react-three-fiber'
<Canvas >
    <ambientLight />
    <Controls />
    <Box imageURLs={imageURLs}/>
</Canvas>
```
<img width="850" alt="Screen Shot 2563-10-15 at 15 49 11" src="https://user-images.githubusercontent.com/66902967/96100202-5118e480-0efe-11eb-8c83-df1410ed44fe.png">

to

```
import { VRCanvas } from '@react-three/xr'
<VRCanvas >
        <ambientLight />
        <Controls />
        <Box imageURLs={imageURLs}/>
</VRCanvas>
```
<img width="980" alt="Screen Shot 2563-10-15 at 15 49 24" src="https://user-images.githubusercontent.com/66902967/96100344-79a0de80-0efe-11eb-8169-1106916e5850.png">

but the background colour has been faded to the picture above compared 
to the normal one. I don't know what is the problem. Can anyone suggest me how to solve it? Thank you a lot

**Comment by sniok** [comment]
VRCanvas enables `colorManagement` property of the react-three-fiber `Canvas` component. You can try disabling it `<VRCanvas colorManagement={false}` or try setting different options for tone mapping and output encoding
`<VRCanvas colorManagement={false} onCreated={({ gl }) => {
      gl.toneMapping = THREE.ACESFilmicToneMapping // you can try different options here 
      gl.outputEncoding = THREE.sRGBEncoding // and here
}>`

**Comment by chanawee-jan** [comment]
Thank you so much for the quick fix!
