### ISSUE TITLE
'DefaultXRControllers' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by Enijar** [pmndrs/react-xr#161]
I just upgraded to v4 and I get this error:

![Screenshot 2022-07-18 at 17 30 24](https://user-images.githubusercontent.com/5284715/179559068-1bbf6a44-ca3a-4908-a411-6f30737b82fa.png)

I can fix this error by rendering the controllers manually, like this:

```jsx
const controllers = useXR((state) => state.controllers);

return (
  <>
    {controllers.map((controller, index) => {
      return <primitive key={index} object={controller} />;
    })}
  </>
);
```

**Comment by CodyJasonBennett** [comment]
Thanks, published a fix in [`4.0.1`](https://github.com/pmndrs/react-xr/releases/tag/v4.0.1).
