### ISSUE TITLE
Can we customize "ENTER VR" button?

### ISSUE THREAD

**Issue by chanawee-jan** [pmndrs/react-xr#17]
Hello,

Can we customize the button which is used to enter VR mode in `<VRCanvas>` with our style?

<img width="173" alt="Screen Shot 2563-10-21 at 16 37 04" src="https://user-images.githubusercontent.com/66902967/96702563-10b4dd00-13bc-11eb-845e-a7404a98e83e.png">

Thank you

**Comment by sniok** [comment]
Hi, yes you can customize this button by making your own VRButton based on [this one](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/webxr/VRButton.js) which is used by default. 

After that you can replace default button with your own by passing it to the VRCanvas like this:
```js
import CustomVRButton from "./CustomVRButton";

<VRCanvas onCreated={({ gl }) => {
   document.body.appendChild(CustomVRButton.createButton(gl))
}}/>

```

**Comment by chanawee-jan** [comment]
Thank you so much
