### ISSUE TITLE
XRButton in VRCanvas is not updated when exiting VR mode 

### ISSUE THREAD

**Issue by AlaricBaraou** [pmndrs/react-xr#172]
I tested this sandbox https://codesandbox.io/s/react-xr-simple-demo-8i9ro with the latest version ( 4.1.2 ) and after exiting VR, the button still shows 'EXIT VR', which prevent the user from returning in VR without refreshing the page. 

It was working correctly in 3.5, I can take a look at this and try to fix it probably in the next 24h.

Edit: nevermind looks like I was a bit optimistic about my estimation, I'll take a look as soon as I can

**Comment by CodyJasonBennett** [comment]
Have a fix started in #176. Can backport to 3.6.x.

**Comment by CodyJasonBennett** [comment]
Fixed in 4.1.4 and 3.6.6.
