### ISSUE TITLE
XRSession.requestReferenceSpace() unsupported experimental feature

### ISSUE THREAD

**Issue by itsezc** [pmndrs/react-xr#179]
Currently `XRSession.requestReferenceSpace()` is not supported (via [CanIUse](https://caniuse.com/mdn-api_xrsession_requestreferencespace)) and throws errors on Firefox, this feature needs to be polyfilled or disabled on non Chrome / Edge based browsers.

Else, we face errors like the following:
```NotSupportedError: The unbounded reference space is not supported by this session.```

**Comment by CodyJasonBennett** [comment]
This is not actionable on our end. We can't disable it -- it's imperative to WebXR rendering, and it's not something we're able to polyfill hence why WebXR is not possible on iOS.
