### ISSUE TITLE
Exit VR button is not working 

### ISSUE THREAD

**Issue by flaaudwls** [pmndrs/react-xr#187]
- Enter VR works, but after quit the VR scene, Exit VR button does not work.
- onMove of Interaction is a really good feature, but state update is not working inside this function. In the earlier version, state update was working properly, just there was no onMove method, so I had to find the intersection point in useFrame with hoverState while controllers moving.

**Comment by saitonakamura** [comment]
You may want to update to update to https://github.com/pmndrs/react-xr/releases/tag/v5.0.1 for proper onMove

**Comment by CodyJasonBennett** [comment]
Published a fix in [`v4.1.7`](https://github.com/pmndrs/react-xr/releases/tag/v4.1.7) (backporting onMove fixes) and [`v5.0.2`](https://github.com/pmndrs/react-xr/releases/tag/v5.0.2).
