### ISSUE TITLE
AR Regression - Camera position does not update

### ISSUE THREAD

**Issue by bknill** [pmndrs/react-xr#194]
Since 3.5 there has been a regression, camera position does not appear to change, camera rotation does - but the object moves away when you move your device towards in AR.  You expect to be able to move the camera around the object, i.e. it is fixed in position. 

3.5.0 works as expected https://codesandbox.io/s/8w8hm
5.0.4 does not work https://codesandbox.io/s/react-xr-simple-ar-demo-forked-kdj1ui

**Comment by bknill** [comment]
@CodyJasonBennett  did you ever get any help with this ?

It's an annoying one - the old example still works great!

**Comment by CodyJasonBennett** [comment]
I believe it's an issue with the reference space. It should be `local` rather than `local-floor` (default) for handheld. I'll have to test on Android hardware in a moment.

```jsx
<XR referenceSpace="local">
 // ...
</XR>
```

**Comment by bknill** [comment]
Hey I tried that and it just disappears (back trying to make this work again)

https://codesandbox.io/s/react-xr-simple-ar-demo-forked-kdj1ui?file=/src/App.tsx

Do you have an example with that AR demo working on Android?

**Comment by bknill** [comment]
Actually after I upgraded everything it is working cheers
