### ISSUE TITLE
WebXR Viewer

### ISSUE THREAD

**Issue by Francois-Laberge-Bose** [pmndrs/react-xr#20]
Hi,

The one demo linked to on the read me looks likes pass through mobile AR. How do I check out that demo? Use WebXR Viewer?

**Comment by sniok** [comment]
AR demo works with any WebXR compatible device/browser. For android that can be chrome and for iOS you can use mozilla's WebXR Viewer

**Comment by Francois-Laberge-Bose** [comment]
I figured out my confusion. WebXR Viewer on iOS doesn't work from the sandbox preview, you have to open the URL directly. See video. 
https://drive.google.com/file/d/1l9eL7Ib-PxnMn_d4J3Tl4TF8yL5D9oMM/view?usp=sharing.

Not sure if someone wants to tweak the README.md to have the image link go straight to the demo output page, not the source and have the sandbox/source be a different window?

**Comment by Francois-Laberge-Bose** [comment]
This works:
https://8w8hm.csb.app/

This does not:
https://codesandbox.io/embed/react-xr-simple-ar-demo-8w8hm?codemirror=1
