### ISSUE TITLE
Hand mesh not visible after tracking lost/restored

### ISSUE THREAD

**Issue by donmccurdy** [pmndrs/react-xr#213]
**Description:**

When hand tracking is lost then restored (e.g. after hands are out-of-view for a brief time), the hand mesh sometimes does not become visible again, and will not reappear without a restart of the XR session. Interaction continues to work fine, so it's clear that react-xr knows where the hands actually are, but the mesh is not shown.

I've been trying to track down the cause here but haven't figured out which layer (react-xr? three-stdlib? three.js? Quest?) the problem is coming from... filing the issue in case others have ideas. Thanks!

**Steps to reproduce:**

1. Run `yarn dev`, open the default scene, and confirm hand models appear
2. Move hands out of view for a few seconds, then return them to view
3. One or both hands may not appear, and will remain permanently invisible (or offscreen?). Interaction continues to work, suggesting that hand position has been recovered but the mesh is gone.

***

https://user-images.githubusercontent.com/1848368/201758640-fa8b036b-0d0c-4766-b4ba-c6808ab06659.mov

In the screen capture above, note the "Oculus" icon shown above the (missing) right hand.

***

- Device: Quest 2
- Browser: Meta Quest Browser 24.2.0
- Version: [`HEAD`](https://github.com/pmndrs/react-xr/commit/8d8250d1a860236017334e779dd8fec91411b488)

**Comment by saitonakamura** [comment]
https://discord.com/channels/740090768164651008/749648291049898074/1055180683703754752 might be related

**Comment by abernier** [comment]
confirmed on my side too, cf. https://discord.com/channels/740090768164651008/749648291049898074/1055170169451843624

**Comment by CodyJasonBennett** [comment]
Fixed in [v5.1.2](https://github.com/pmndrs/react-xr/releases/tag/v5.1.2) with #227, thanks to @bodo22. Tracking related issues in R3F in https://github.com/pmndrs/react-three-fiber/issues/2679.

**Comment by donmccurdy** [comment]
Confirmed, thank you! 🙏
