### ISSUE TITLE
VR button shows VR unsupported

### ISSUE THREAD

**Issue by brownie11636** [pmndrs/react-xr#217]
Hello, I try to immigrate my Threejs XR codes to a NextJS project, and suffer an unexpected problem.

Are there any expected causes for the following problem?

VR button in my app show VR unsupported when I approach via the oculus browser or mobile browsers with cardboard.
Also, console.log(navigator.xr) answered undefined.
However, everything works well with chorme webXR emulator on the desktop.

Also, In public examples on this github like (https://codesandbox.io/s/v4uet),
the VR buttons work well when I run them in codeSandbox in the oculus browser.
However, when I download codes and run them on localhost, it also shows VR unsupported.
Of course, it still works well with chorme webXR emulator

I also tried just adding only VR button in React-Three-Next starter (https://github.com/pmndrs/react-xr), it also resulted VR unsupported

The oculus browser or mobile browsers doesn't have any problem in pure ThreeJS webXR project or webXR example including my custom projects and public examples (https://immersive-web.github.io/webxr-samples/ ),(https://threejs.org/examples/?q=webxr)

**Comment by rekliner** [comment]
The like cause is that VR sessions can only be started over https.  the default setup for CRA and Next starter apps is to host over http://localhost:3000.  For CRA you can simply add a .env file with the contents `HTTPS=true` .  For NextJs try adding the next-dev-https package:
`npm i npx next-dev-https
npx next-dev-https -s`

**Comment by brownie11636** [comment]
@rekliner 
Thank you so much!! Now it works well.
