### ISSUE TITLE
[Question] How to move player via joystick within VR?

### ISSUE THREAD

**Issue by JenniferFalkenstein** [pmndrs/react-xr#218]
Is it possible to let the player move around in a VR-world with one of the joysticks on the controller? 
I already read about changing the position of the player via `const { player } = useXR()` and then configure it by setting `player.position.x/y/z` to some value.
But I still need to access the joystick event somehow, right? How do I do that? 😄

**Comment by AlaricBaraou** [comment]
Hello Jennifer, you can access the controllers by using [the useController() hook ](https://github.com/pmndrs/react-xr#usecontroller)

Then on each frame you can read the current value of each input just like the with [the GamePad API](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API) 

It could look something like this
```
  const leftController = useController('left')
  const rightController = useController('right')

  useFrame((state, delta, XRFrame) => {
    if (XRFrame) {
      if (rightController) {
        const rightGamePad = rightController.inputSource.gamepad
       /* right joystick values are stored in rightGamePad.axes */
      }
      if (leftController) {
        const leftGamePad = leftController.inputSource.gamepad
        /* left joystick values are stored in leftGamePad.axes */
      }
    }
  })
```

**Comment by JenniferFalkenstein** [comment]
Thank you very much! It helped alot 😄
