### ISSUE TITLE
Can I change the camera pivot or position of ARCanvas? 

### ISSUE THREAD

**Issue by Frander** [pmndrs/react-xr#22]
I'm trying with this, but doesn't work 
<ARCanvas sRGB camera={{ position: [0, 0, 55] }}>
        <App />
      </ARCanvas>

**Comment by sniok** [comment]
hi, you can get access to camera and change its' position by getting it from XRManager 

```js
const { camera } = useThree()
const cam = gl.xr.isPresenting ? gl.xr.getCamera(camera) : camera
```
