### ISSUE TITLE
how to handle controller events for device-specific buttons?

### ISSUE THREAD

**Issue by vgrafe** [pmndrs/react-xr#23]
Hi!

I am trying to migrate a r3f codebase to react-xr and have an Oculus Quest to test on. Those controllers have an analog stick and A/B buttons each... is there a way to handle events related to those inputs?

**Comment by msub2** [comment]
You will likely need to reference the WebXR Gamepads Module and access the correct buttons/axes on the Gamepad object in the XRController inputSource

**Comment by vgrafe** [comment]
Perfect, thanks!
