### ISSUE TITLE
[Question] Oculus Quest 2 support with latest Chrome/Firefox

### ISSUE THREAD

**Issue by getarun** [pmndrs/react-xr#255]
Hello,

I try to run the examples, but get stuck with an AR unsupported Text in the buttom button.
I installed Oculus software, connected the Quest 2 via Air Link to the computer and ran the local examples.
The demos show up, but each shows "AR unsupported", on both chrome and firefox. Closing Oculus software doesn't change anything. Online code examples show the very same error. Switching from Oculus to the OpenXR runtime does not change anything.

Feels like I am missing some dependencies :(

Any ideas?

Additional information from browser console (chrome):
- navigator.xr.isSessionSupported('inline').then(console.log) => true
- navigator.xr.isSessionSupported('immersive-ar').then(console.log) => false
- navigator.xr.isSessionSupported('immersive-vr').then(console.log) => false

Versions:
- Windows 10
- node 14.18.1
- chrome 110.x
- firefox 110.x
- oculus runtime version: 1.81.0
  - API version: 1.0.24
- WindowsMixedReality runtime version: 112,221,2002
  - API version: 1.0.24

Thank you :)

**Comment by Ermit3** [comment]
Hi,
I had the same problem, I used this solution #217

**Comment by getarun** [comment]
Secure Context is provided when calling localhost:xxxx, as I understant correctly. Will have a look into your proposed workaround. 
TY

**Comment by CodyJasonBennett** [comment]
That is correct, WebXR requires a secure origin to use which can either be via https or any protocol over localhost. I just released [`v5.3.0`](https://github.com/pmndrs/react-xr/releases/tag/v5.3.0) which will give better hints than "unsupported" for this case.

**Comment by getarun** [comment]
Ty for that, my issue seems to be somewhere else.
```
navigator.xr.isSessionSupported('immersive-ar')
```
return false. No clue why :/

**Comment by saitonakamura** [comment]
@getarun I don't think `immersive-ar` is supported in oculus link mode at all. Maybe there's a way to force use of mixed reality runtime for the quest 2, but I'm not sure if it's even possible

**Comment by saitonakamura** [comment]
Best way to check whether its react-xr fault or not is to use https://immersive-web.github.io/webxr-samples/tests/
