### ISSUE TITLE
Misleading  example in readme

### ISSUE THREAD

**Issue by vgrafe** [pmndrs/react-xr#26]
Hi!

Following the example given to parent VR HMD/controllers [did not yield the expected results](https://discord.com/channels/740090768164651008/749648291049898074/797102570635132950). Only controllers would be bound to the player mesh.

A solution was found and explained [there](https://discord.com/channels/740090768164651008/749648291049898074/798570458701889546). Should the readme be updated? Or maybe we did something wrong?

Thanks!

**Comment by sniok** [comment]
Hi, yes the whole camera position and controller parenting is a mess right now. I want to figure out more convenient way to do this and I'll update readme and code

**Comment by sniok** [comment]
This is now solved by `Player` component that allows for convenient way to position 'user' in space. https://github.com/pmndrs/react-xr#player   
If you still have question/doubts/ideas feel free to open a new issue
