### ISSUE TITLE
Teleportation Component

### ISSUE THREAD

**Issue by richardanaya** [pmndrs/react-xr#260]
It would be awesome if there was an easy way to just add a component that lets a user teleport around on intersection with child elements.

It seems like the teleportation example uses reference spaces for this.

https://threejs.org/examples/webxr_vr_teleport.html

**Comment by laffan** [comment]
@richardanaya I've had success riffing on @mwmwmw 's component that does exactly that : https://codesandbox.io/s/e3yc3

**Comment by richardanaya** [comment]
Submitted initial PR for support https://github.com/pmndrs/react-xr/pull/263

You can see it in action on https://avatarposer.com/
