### ISSUE TITLE
XRButton styling

### ISSUE THREAD

**Issue by Soham1803** [pmndrs/react-xr#267]
Props should be added to the XRButton component to position and style the XRButton.

**Comment by CodyJasonBennett** [comment]
This is already supported, XRButton is an HTML button and accepts all of its props in addition to the XRButton interface.

**Comment by CodyJasonBennett** [comment]
I'm not sure how to help you, this is default DOM behavior; this library does not modify its behavior other than add listeners to initialize a WebXR session.

**Comment by Soham1803** [comment]
I'm extremely sorry, I think I misunderstood something. I thought it was a custom react component. Sorry, I'll close the issue.
