### ISSUE TITLE
Hand tracking resets hand position if tracking lost causing weird visual effects

### ISSUE THREAD

**Issue by Ledzz** [pmndrs/react-xr#273]
If the tracking is lost, hands are reset to (0, 0, 0) position.

**To reproduce:** 
- Go to Hands Tracking Demo: https://codesandbox.io/s/gczkp
- Move your hand behind your head, so it loses tracking
- See downwards

**Actual result:**
You see a hand model in idle state in (0,0,0) coordinates (where you stand)

**Expected result:**
Hand model is hidden

My idea to fix it was to find parent element (armature itself) and if its position is strictly (0,0,0) just hide the hand.
But I find this check too loose: maybe the coordinates will be not exacly 0.
Do you have any ideas?

**Comment by CodyJasonBennett** [comment]
I believe events are dispatched when the input method changes. Will have to see if that's true for hands in this case or only if controllers are then activated.

**Comment by Ledzz** [comment]
I've checked, events are dispatched when the tracking is lost. I'll try to fix it tomorrow.
