### ISSUE TITLE
Attempting to add <XR> to an open source proj, but unclear how to debug

### ISSUE THREAD

**Issue by jeffscottward** [pmndrs/react-xr#281]
https://github.com/Lunakepio/death-star-trench-run/tree/VR

On this branch of this Star Wars trench run demo, I added `<XR>`, and get no errors, but when entering XR, I get a blank screen.
This isn't a bug with this repo but rather a discussion point on how to debug a session if you lack the hardware.

I have the WebXR debugger from Meta in my chrome dev tools, and hitting the XR button makes the screen go black. Can you only preview in a real headset? Is there some sort of config I'm missing? Etc etc

**Comment by CodyJasonBennett** [comment]
three.js has pending fixes that enable postprocessing since the introduction of layers now years ago -- https://github.com/mrdoob/three.js/pull/26160. Your intuition for debugging is fine, however. Try with and without an effects composer.
