### ISSUE TITLE
Hand-tracking hardware?

### ISSUE THREAD

**Issue by maurocolella** [pmndrs/react-xr#292]
Hi, I am sorry if this is the wrong place, but I wanted to ask what is the hardware used in the hand tracking demos?

**Comment by CodyJasonBennett** [comment]
Meta Quest 2 is what we use mostly, but anything that supports hands as an input scheme is supported.

**Comment by maurocolella** [comment]
Thank you.

**Comment by saitonakamura** [comment]
AFAIK only Meta Quests (1, 2 and Pro, and obviously 3 in the near future) support hand tracking. Pico Neo 4 does support hand tracking in its own interface, but not in WebXR

You can also debug it with https://github.com/meta-quest/immersive-web-emulator/, it does support hand tracking emulation
