### ISSUE TITLE
Enabling hands disables rays

### ISSUE THREAD

**Issue by patrickkeenan** [pmndrs/react-xr#299]
When hands are recognized, rays disappear. This is a problem if you want to interact with far away objects by pinching. The solution is probably to have a argument to enable rays while hand tracking is active.

https://github.com/pmndrs/react-xr/blob/4d23eb88daa5ae484de05fa157cdc7fe366c2e47/src/Controllers.tsx#L169

**Comment by CodyJasonBennett** [comment]
You can enable visibility yourself via `rayMaterialProps` or `<Controllers rayMaterial={{ visible: true }} />`.

**Comment by chenzhutian** [comment]
setting `<Controllers rayMaterial={{ visible: true }} />` won't show the hand since the key will be converted to `material-visible`
