### ISSUE TITLE
useHitTest doesn't work

### ISSUE THREAD

**Issue by funwithtriangles** [pmndrs/react-xr#33]
When trying to use the `useHitTest` hook, I encounter this error message:

```
TypeError: Cannot read property 'requestAnimationFrame' of null
    at Object.current (index.js:346)
    at renderGl (web.js:70)
    at web.js:1156
    at onAnimationFrame (three.module.js:22288)
    at Object.onAnimationFrame [as callback] (three.module.js:12286)
    at XRSession$1.<computed>.onDeviceFrame (<anonymous>:1281:42)
```

Looking at the `useHitTest` function (`XR.tsx`), `sessionRef.current` returns `null` on line 77. Unfortunately I'm not exactly sure how all of this is working so it's a bit tricky for me to debug any further.

I am using the appropriate 'sessionInit={{ requiredFeatures: ['hit-test'] }}' property on the 'ARCanvas' tag. I think it would be great to get a demo up and running for this feature.

**Comment by sniok** [comment]
Thanks for reporting the bug! It is now fixed in version 2.0.1. Here's a working example https://codesandbox.io/s/react-xr-usehittest-demo-5iff9?file=/src/App.tsx
