### ISSUE TITLE
React-xr examples not working 

### ISSUE THREAD

**Issue by ybinstock** [pmndrs/react-xr#35]
I've followed the steps on https://github.com/pmndrs/react-xr/tree/master/examples, but I got the following error

"Cannot read property 'requestAnimationFrame' of null at Object.current". 

What's slightly weird is that the sandbox example is working fine on my device - https://codesandbox.io/s/react-xr-simple-ar-demo-8w8hm.

**Comment by carllx** [comment]
It should be work.

update the packet
```json
"dependencies": {
    "@react-three/drei": "3.10.2",
    "@react-three/xr": "2.0.0",
    "@types/react": "17.0.3",
    "@types/react-dom": "17.0.2",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-scripts": "4.0.3",
    "react-three-fiber": "5.3.19",
    "three": "0.126.1"
  },
```

import drei correctly

```javascript
// import { Text } from '@react-three/drei/Text'
import { Text } from '@react-three/drei'
```
[react-xr simple AR demo (forked)](https://codesandbox.io/s/react-xr-simple-ar-demo-forked-kxqek?file=/src/App.tsx)

**Comment by sniok** [comment]
yeah useHitTest was broken, it's fixed now. Make sure to use latest three version. Here's a working example of useHitTest hook https://codesandbox.io/s/react-xr-usehittest-demo-5iff9?file=/src/App.tsx
