### ISSUE TITLE
Add access to XRFrame 

### ISSUE THREAD

**Issue by ThomasRutzer** [pmndrs/react-xr#37]
Hi, 

I made a little demo which includes **react-xr**. And for that, I wrote an [ `useXRFrame` hook. ](https://github.com/ThomasRutzer/webxr-image-targets-hole/blob/dev/src/utils/useXRFrame.js). It basically passes the current `XRFrame` to a callback in the loop of a XR session, so it can be used in a component like this: 
` useXRFrame(callback) `

Maybe it can also be useful for this package?  [XRFrame](https://developer.mozilla.org/en-US/docs/Web/API/XRFrame) holds some useful information about an active XR session.

**Comment by sniok** [comment]
Oh yeah this kind of hook would be useful! Ideally, of course, XRFrame would be passed in `useFrame` hook of r3f but this also works nicely. PR with it would be greatly appreciated

**Comment by ThomasRutzer** [comment]
Nice, I try to make a PR ready the next days. 

I think it cannot easily be combined with `useFrame` since it is based on the raf of an XR session. But still I agree it would be better to collect multiple `useXRFrame` into one raf-loop (this is something I suppose `useFrame` is doing somewhere). Otherwise using a lot of `useXRFrame` in various components could compromise performance. This could also be a future optimization.
