### ISSUE TITLE
Can you view HTML or use react-three-gestures  in AR?

### ISSUE THREAD

**Issue by Alex23925** [pmndrs/react-xr#38]
Working on a project to display a few meshes in AR but useDrag from react-three-gestures doesn't seem to work so I opted for some HTML slider to move the position around but does not seem like HTML appears in AR mode. Does anyone know how to achieve this? Any help or pointing me in the right direction would be great, thx in advance 🙏

**Comment by sniok** [comment]
There is a draft for an experimental feature that allows placing DOM element in AR session. 

https://immersive-web.github.io/dom-overlays/
https://github.com/immersive-web/dom-overlays/blob/main/explainer.md

It appears that it's already implemented in Chrome but I haven't looked into it that much yet

**Comment by WhidRubeld** [comment]
Example

```
const overlay = document.getElementsByTagName('body')[0]

export default function Scene() {
    return (
      <ARCanvas sessionInit={{
           optionalFeatures=['dom-overlay'],
           domOverlay = { root: overlay } 
      }}>
          ....
      </ARCanvas>
    )
}
```

**Comment by WhidRubeld** [comment]
react-use-gesture can be used in AR. You can easily implement movement, rotation, etc.

**Comment by sniok** [comment]
thanks @WhidRubeld !

**Comment by chillbert** [comment]
I tried the the [Html component from drei](https://github.com/pmndrs/drei?tab=readme-ov-file#html), it is not working in the AR session (nor in VR session); am I forgetting something? (nothing specified).
