### ISSUE TITLE
Help with useHitTest

### ISSUE THREAD

**Issue by QusstW** [pmndrs/react-xr#40]
Hello, I'm a beginner developer. For a week now I have been suffering and do not understand how useHitTest works. As I have already understood, this hook allows you to determine the hit in the AR environment. But how to use it to achieve the placement of any object on a real surface. I will be glad for any help or hint.

**Comment by sniok** [comment]
Hi! 

useHitTest hook will call the callback function once it detects a real surface. It will pass two arguments: a matrix and XRHitTestResult

Let's look at the simplest example 

```js
function HitTestExample() {
  const ref = useResource()

  useHitTest((hit) => {
    hit.decompose(ref.current.position, ref.current.rotation, ref.current.scale)
  })

  return <Box ref={ref} args={[0.1, 0.1, 0.1]} />
}
```

in this example we want to place a box on a real surface every frame

` useHitTest((hit) => {`
Here `hit` is a [Matrix4](https://threejs.org/docs/#api/en/math/Matrix4) object which contains position and rotation of a position on a real surface. 

Next, we can copy position of the `hit` to the our Box mesh 
`hit.decompose(ref.current.position, ref.current.rotation, ref.current.scale)`

the effect of this is that as soon as there's a real plane detected, on every frame the Box will be placed on that plane

Here is the working example on codesandbox: https://codesandbox.io/s/react-xr-usehittest-demo-5iff9?file=/src/App.tsx

**Comment by QusstW** [comment]
Thank you very much!!!
