### ISSUE TITLE
how to apply hit-test to model

### ISSUE THREAD

**Issue by carmandale** [pmndrs/react-xr#47]
The sample uses useResource, which doesn't work with v6, so I switched to useRef.

useHitTest seems to be working, but how do I make a tap event "plant" the hitTest location? is there an example of that?

I tried adding 'hitMatrix' to `useHitTest((hitMatrix, hit) => {
  // use hitMatrix to position any object on the real life surface
})`

but when I add hitMatrix, I get this error:
`Uncaught TypeError: hit.decompose is not a function
    at App.js:60
    at XRSession.<anonymous> (index.js:357)`

if I remove hitMatrix, and just:
`useHitTest((hit) => {
    hit.decompose(
      ref.current.position,
      ref.current.rotation,
      ref.current.scale
    );
  });`

the hit testing will work, but I am not sure how to make the model "stick" to the plane.

thanks,
Dale

**Comment by sniok** [comment]
Hi, useHitTest fires continuously on every frame it registers a hit against a real life surface

to fix model position in place you'll need to copy and store position after some kind of event (for example click)

here's a rough pseudocode of what that would look like 

```jsx
// Store hit position from current frame
const hit = useRef()
useHitTest(hit => hit.current = hit);

// Reference to a model
const mesh = useRef()

// some event handler, for example when user clicks on the canvas
{
   // Set our model position to the position of the current hit
   hit.current.decompose(mesh.current.position, mesh.current.rotation ,...)
}

```

**Comment by carmandale** [comment]
Thank you so much,

A few questions if you don’t mind.

Is there any performance penalty to this implementation vs direct threejs?
And do you feel like this is ready for a real production project?

Just want to get your sense of the state of things before I go full speed in.

Thanks,
Dale

**Comment by sniok** [comment]
react-xr is just a couple of components and hooks for react-three-fiber 
there are no limitations compared to threejs and there's no additional overhead

**Comment by tsuki1646** [comment]
I followed your code, scale is good, but hard to rotate!!!

**Comment by nirajmohanrana** [comment]
> The sample uses useResource, which doesn't work with v6, so I switched to useRef.
> 
> useHitTest seems to be working, but how do I make a tap event "plant" the hitTest location? is there an example of that?
> 
> I tried adding 'hitMatrix' to `useHitTest((hitMatrix, hit) => { // use hitMatrix to position any object on the real life surface })`
> 
> but when I add hitMatrix, I get this error: `Uncaught TypeError: hit.decompose is not a function at App.js:60 at XRSession.<anonymous> (index.js:357)`
> 
> if I remove hitMatrix, and just: `useHitTest((hit) => { hit.decompose( ref.current.position, ref.current.rotation, ref.current.scale ); });`
> 
> the hit testing will work, but I am not sure how to make the model "stick" to the plane.
> 
> thanks, Dale

Hey @carmandale did you solved this issue, i am try to perform that solution but it throws error can you please help me in it

**Comment by laffan** [comment]
Hi! I'm working on controlled interactions, like limiting grab to the X/Z axis.  Currently it works great just offsetting controller position, but I'd like the control point to be the ray intersection rather than controller offset.  

useHitTest seems like it would be a good fit for this. I've got a working example of the offset solution here : https://codesandbox.io/s/r3f-xr-drag-demo-sg3krv?file=/src/App.js 

Given @sniok 's suggestion  above, I thought I might be able to adjust that and make it something like this :  

```
const hit = useRef()
useHitTest(hit => hit.current = hit);

   useFrame(() => {
    const controller = grabbingController.current
    const group = groupRef.current
    if (!controller) return

    const newPosition = new THREE.Vector3().copy(group.position)
    newPosition.x = hit.current.position.x
    newPosition.z = hit.current.position.z

    // Set the Y position of the new vector to the current Y position of the group
    newPosition.y = group.position.y

    // Set the new position of the group
    group.position.copy(newPosition)
    previousTransform.copy(hit.current.matrixWorld).invert()
  })
```

But this causes the headset to go dark.  I have no idea what's going on there don't seem to be a lot of resources for this at the moment.  Thanks in advance!
