### ISSUE TITLE
How come RayGrab is not documented?

### ISSUE THREAD

**Issue by ffdead** [pmndrs/react-xr#53]
I've used this handy component in the past but notice it's still not documented. Is it not safe to use `<RayGrab>` for some reason?

**Comment by clintonmedbery** [comment]
Just adding my 2 cents how it would be great if this had an example.

**Comment by CodyJasonBennett** [comment]
I don't see anything dangerous about `<RayGrab />`, but it's not too extensible atm. I've gone ahead with preliminary docs.
