### ISSUE TITLE
@react-spring/three useSpring stops updating in XR session

### ISSUE THREAD

**Issue by ffdead** [pmndrs/react-xr#54]
This is a duplicated bug report from https://github.com/pmndrs/react-spring/issues/1518

I'm not sure if this a bug related to @react-spring/three, @react-three/fiber, @react-three/xr or a combination of all three.

Feel free to close if you think this bug relates to react-spring only and not this library. 

## To Reproduce

1. Load repro link below
2. The mesh changes scale on a timer ever 1s - this is animated with a spring
3. Start a VR session
4. The mesh stops animating scale and stays at the scale it was when the xr session was started

## Expected behavior

The mesh should continue to animate scale inside the XR session.

## Link to repro 

https://codesandbox.io/s/react-xr-react-spring-bug-fkzt3?file=/src/index.tsx

## Environment

- `@react-spring/three` >= v9.0.0
- `@react-three/fiber` >= v6.0.3
- `@react-three/xr` >= v2.1.0
- `react` v17.x

Works as expected with the following old versions: 
- `@react-spring/three` v9.0.0-rc.3
- `react-three-fiber` v5.x.x
- `@react-three/xr` v2.0.1

**Comment by driescroons** [comment]
going to leave the same reply here as I don't think this is a react-xr issue. 

from [#1518](https://github.com/pmndrs/react-spring/issues/1518):

> I recently migrated to all newest versions and noticed the issue. I've updated your codesandbox with the packages I was using before and can confirm that these versions do work in the oculus browser:
> https://codesandbox.io/s/react-xr-react-spring-bug-forked-98v38?file=/src/index.tsx
> 
> `@react-spring/three@9.1.2` => `@react-spring/three@9.0.0-rc3`
> `@react-three/fiber@6.1.5` => `react-three-fiber@6.0.13`
> 
> I did not have to change the react-xr version because that did not seem to cause the issue.
