### ISSUE TITLE
'HTTPS' is not recognized as an internal or external command when 'yarn start' in /exemples

### ISSUE THREAD

**Issue by Thebinoman** [pmndrs/react-xr#55]
I get this error: "'HTTPS' is not recognized as an internal or external command, operable program or batch file." when I run 'yarn start' from the 'examples' folder.

How to reproduce:
1. Have a Windows PC.
2. Install node.js and yarn
3. git clone https://github.com/react-spring/react-xr
4. cd react-xr
5. yarn
6. cd examples
7. yarn
8. yarn start

**Comment by CodyJasonBennett** [comment]
Are you on Windows? It doesn't seem like your machine knows it's trying to set an environment variable ([script here](https://github.com/pmndrs/react-xr/blob/master/examples/package.json#L6)).

I believe prefacing this with `set HTTPS=true && react-app-rewired start` should work, as far as compatibility goes.

**Comment by Thebinoman** [comment]
Yes it worked, but now I have endless errors
![image](https://user-images.githubusercontent.com/18375738/119125088-11891c80-ba3a-11eb-93e7-62b2e5df29c7.png)

**Comment by CodyJasonBennett** [comment]
What device are you using? Quest 1, 2, Valve, MR?

**Comment by Thebinoman** [comment]
> What device are you using? Quest 1, 2, Valve, MR?

Rift

**Comment by ohmygaugh-crypto** [comment]
After making the above changes as a Windows user... Which port does this run on by default?

**Comment by CodyJasonBennett** [comment]
@ohmygaugh-crypto, instructions will appear in your console. Examples will run on https://localhost:3000 as configured.

**Comment by sakshi3579** [comment]
'https:' is not recognized as an internal or external command,
operable program or batch file. 
I'm facing this error when I used my new git repo https

**Comment by charles-smeeth** [comment]
how do I fix this please I'm still new at this.
'https:' is not recognized as an internal or external command,
operable program or batch file.

**Comment by CodyJasonBennett** [comment]
I'd refer to https://github.com/pmndrs/react-xr/tree/master/examples. `HTTPS=true` is not cross-compatible to do, but you can otherwise `npx cross-env HTTPS=true`.

**Comment by heykarna** [comment]
'https:' is not recognized as an internal or external command,
operable program or batch file. 
what to do

**Comment by CodyJasonBennett** [comment]
See my first comment.

**Comment by HamzaAryanSapnil** [comment]
> Are you on Windows? It doesn't seem like your machine knows it's trying to set an environment variable ([script here](https://github.com/pmndrs/react-xr/blob/master/examples/package.json#L6)).
> 
> `set HTTPS=true && react-app-rewired start` should work if you want to go ahead and submit a PR.

i have this problem 'https:' is not recognized as an internal or external command, in my windows. where do I need to set https = true do you have any tutorial video? i was cloning a git repo and I face this problem
