### ISSUE TITLE
Support for Hololens

### ISSUE THREAD

**Issue by emmmplayer** [pmndrs/react-xr#59]
Hi,

I apologize for posting this question here, in case this is not appropriate. 

I have looked into the examples and I'm trying to understand if react-xr supports Microsoft Hololens Hands recognition/interaction? if not, do you have any plans to support it? 

Thanks in advance,
EM.

**Comment by mwmwmw** [comment]
This is not a definitive answer, but if the Hololens 2 follows the WebXR spec, then the hands will be available as a controller. 

This (https://www.youtube.com/watch?v=MlGdZ4_RELQ) Firefox Reality demo demonstrates hands working for Hololens. You should be able to access those in React XR using the `useXR()` hook.

**Comment by emmmplayer** [comment]
Thank you for the answer! I will dive into it.

**Comment by Utopiah** [comment]
Hi, I didn't try hand tracking but otherwise worked well https://twitter.com/utopiah/status/1399822972286865409 so XR works for sure.

If @emmmplayer you either progress there or get stuck let me know.
