### ISSUE TITLE
onCreated prop on the VRCanvas prevent 'ENTERVR' from displaying

### ISSUE THREAD

**Issue by AlaricBaraou** [pmndrs/react-xr#65]
It's pretty straighforward

```
<VRCanvas
      onCreated={({ camera }) => camera.lookAt(0, 2, -2)} // having this prop prevent react-xr from working properly
>
```

having this prop prevent react-xr from working properly.
Because I guess it conflicts with this file 
https://github.com/pmndrs/react-xr/blob/master/src/XR.tsx#L164

**Comment by m0o0scar** [comment]
I'm encountering the same issue, any update here?

**Comment by sniok** [comment]
#66 will fix this issue
