### ISSUE TITLE
Allow custom optional features for VRButton

### ISSUE THREAD

**Issue by CodyJasonBennett** [pmndrs/react-xr#67]
`VRButton` does not allow any customization of the session like `ARButton` does with `sessionInit`.

Since `VRButton`'s `option` parameter has been removed, I propose allowing users to specify `sessionInit` in the `VRButton` as well or optional features, with the addition of [layers support in three](https://github.com/mrdoob/three.js/pull/22060).

```jsx
// Configures layers with R3F (see https://threejs.org/examples/#webxr_vr_layers)
<VRCanvas sessionInit={{ optionalFeatures: [ 'local-floor', 'bounded-floor', 'hand-tracking', 'layers' ] }} />
```

**Comment by andrew-luhring** [comment]
I am 100% an idiot, but how in the actual hell did you actually import VRButton? 
Chrome says:
> Uncaught SyntaxError: The requested module 'https://cdn.skypack.dev/@react-three/xr' does not provide an export named 'VRButton'

when I try:
```js 
import { VRCanvas, VRButton} from 'https://cdn.skypack.dev/@react-three/xr'
```
... actually... is there a page somewhere that lists where to import everything from everything? I've crawled all over this rep and the docs website and I'm lost.

**Comment by CodyJasonBennett** [comment]
@andrew-luhring, I imported on line 1 of [`src/XR.tsx`](https://github.com/pmndrs/react-xr/pull/68/files#diff-e754dca5e92225735d05debdc3c04c0422585d19809c21640b16958ed4914d4dR6) to create bindings for `VRCanvas` and `ARCanvas`.

I don't believe it's intended to be exported separately (as this is a react-focused lib), but you can try changing the path there to `@react-three/xr/src/webxr/VRButton`.

**Comment by andrew-luhring** [comment]
Turns out if you use VRCanvas or ARCanvas, they automatically add buttons for you- BUT if you are using react router or something similar and navigate away from the page, the button gets recreated each time you navigate back; i opened a pull request that should fix that behavior but yeah... kinda annoying that you can't at least specify where/how it looks
