### ISSUE TITLE
Can't use GLB with AR

### ISSUE THREAD

**Issue by Yehoyakim** [pmndrs/react-xr#71]
I was trying to use the test example with a glb object but I have the following problem: if I don't press the AR button, I can see the GLB model loaded, but if I press the "Go to AR" button, the camera does not start and I only see the same page in full screen.

Does anyone know why this happens?

The code:

```
const ThreeViewer = () => {
    function LoadGLB() {
        const gltf = useGLTF("MODEL-URL" , true)
        return <primitive object={gltf.scene} />
    }
    function HitTestExample() {
        const hitPoint = useRef()

        useHitTest((hitMatrix, hit) => {
            hitMatrix.decompose(hitPoint.current.position, hitPoint.current.rotation, hitPoint.current.scale)
        })

        return <Box ref={hitPoint} args={[0.1, 0.1, 0.1]} />
    }

    return (
        <>
            <ARCanvas sessionInit={{ requiredFeatures: ['hit-test'] }} camera={{ position: [0, 0, -0.3] }}>
                <ambientLight />
                <mesh position={[0, 0, 0]}>
                    <LoadGLB/>
                </mesh>
                <pointLight position={[10, 10, 10]} />
                <HitTestExample />
                <DefaultXRControllers />
            </ARCanvas>
        </>
    )
}
```

![1](https://user-images.githubusercontent.com/8935693/125849397-6770ecde-e50f-498f-9f4e-caa9c25c2a3a.PNG)

**Comment by mwmwmw** [comment]
Hi Yehoyakim, 

I don't see anything in your code that could be causing an issue. 

What platform/browser are you using to test with? iPhone? Android? Chrome? Safari?

What happens if you run this example? 
https://7push.csb.app/ 

It's a similar basic setup, but no model loading.

**Comment by Yehoyakim** [comment]
> Hi Yehoyakim,
> 
> I don't see anything in your code that could be causing an issue.
> 
> What platform/browser are you using to test with? iPhone? Android? Chrome? Safari?
> 
> What happens if you run this example?
> https://7push.csb.app/
> 
> It's a similar basic setup, but no model loading.

I am using Chrome on Android via localhost (with https)
The example works correctly

**Comment by Yehoyakim** [comment]
So aparantly se solution was adding React.Suspense like this:
```
<React.Suspense fallback={null}>
                    <mesh position={[0, 0, 0]}>{<LoadGLB/>}</mesh>
</React.Suspense>
```
