### ISSUE TITLE
cannot open locally hosted site in XRviewer

### ISSUE THREAD

**Issue by JakeJustLearning** [pmndrs/react-xr#85]
I followed the examples exactly as they are listed in the react-XR examples to clone the repo, yarn, and then start. I am using an iphone XS with the latest version of the XR viewer and iOS. however when I try to access the locally hosted instance by going to https://<computer's-ip-address.:<port>  with both my computer and iphone on the same network WebXR is not able to access the site. Is there something missing from the instructions for accessing WebXR from a localhost?  do I need to do anything specific to be able top access locally hosted instance?

**Comment by methot-ilya-3ds** [comment]
I believe this is a problem related to the following issue: https://github.com/googlecodelabs/ar-with-webxr/issues/4

I was having the same problem until Is started hosting the site on its own domain using services such as github pages.

**Comment by JakeJustLearning** [comment]
Thanks, Is there anyway to create an SSL for localhost? or can you get around that? because the github pages strategy really makes development a pain.

**Comment by verekia** [comment]
Yes. You can set up a localhost certificate quite easily. You can Google for some tutorials. I just did it and it works great to try my game on my Quest 2 and on my phone. And with hot reloading (even on those devices) that's really a great and lightweight developer experience.

**Comment by camjackson** [comment]
You can also use an HTTPS tunneler like [ngrok](https://ngrok.com/). This also solves [this issue](https://github.com/mozilla-mobile/webxr-ios/issues/189) with the WebXR Viewer on iphone.

**Comment by Creative-Ataraxia** [comment]
> You can also use an HTTPS tunneler like [ngrok](https://ngrok.com/). This also solves [this issue](https://github.com/mozilla-mobile/webxr-ios/issues/189) with the WebXR Viewer on iphone.

but ngrok have no free option to use their http agent correct? so unless you are willing to subscribe, that is not a solution?
