### ISSUE TITLE
useXR() hook providing nothing

### ISSUE THREAD

**Issue by JakeJustLearning** [pmndrs/react-xr#89]
I am working in an `ARCanvas` I include `<DefaultXRControllers> in my canvas as well in the component I create `const {controllers} = useXR` as shown in the documentation. However when I just try to console.log the controllers they are undefined. I am trying to gain access to the information of the controller so I can understand what it is taking in so that I can put it in text on the screen as well as use it to develop more easily. 

Is there a specific way to use the controllers to expose its information in a console.log?

**Comment by JakeJustLearning** [comment]
I am even doing this within another component in the the ARCanvas. How is the controller accessed and connected? Please help. I am working on a project which is very time sensitive as part of my training program. Thank you!

**Comment by mwmwmw** [comment]
Hi Jake, do you have a CodeSandBox link or something I could look at? 

Try this for starters... 

```
const XR = useXR();

console.log(XR);

```

Do you get anything?

**Comment by JakeJustLearning** [comment]
I found that the useXR hook only creates controllers on my iOS device when an active touch input was occurring. so if I was touching my screen then there was a controller created.
