### ISSUE TITLE
Trigger select event on closest object only

### ISSUE THREAD

**Issue by mz8i** [pmndrs/react-xr#97]
I am trying to build an interaction where one of many cubes in the scene can be selected. All the cubes are wrapped separately in an `<Interactive>` component. 

However what I've noticed is that when multiple objects are on the hit ray's path, the interaction will be triggered for all of them. This is a common case since the scene is fully packed with objects.

Would it be desirable to introduce some mechanism that specifies that only the closest object hit by the ray should have an interaction triggered?

I think the workaround right now is to add an onHover/onBlur and store the distances extracted from the intersection objects externally, and work from there... but it seems a bit involved for such a common use case

**Comment by monkyver** [comment]
Any update on this issue? Is there a release plan for this?
