### ISSUE TITLE
AR session blocks re-renders from outer state changes

### ISSUE THREAD

**Issue by mattrossman** [pmndrs/react-xr#98]
**Expected behavior**

A component `<Foo prop={val} />` should re-render when `val` changes state.

**Actual behavior**

If `<Foo prop={val} />` exists inside of an `<ARCanvas />` and the AR session has started, then changing `val` outside of the `<ARCanvas />` will not trigger it to re-render.

By contrast, if the state is created inside of `<ARCanvas />` then its consumer will re-render as expected.

**Examples**

Updating a rotation value (defined outside of the canvas) on an interval. Once the AR session starts the cube stops rotating:
https://codesandbox.io/s/react-ar-missing-render-dflsz?file=/src/App.jsx

In this one, the state is created by a component within the canvas, this time the cube continues rotating after the session starts:
https://codesandbox.io/s/react-ar-missing-render-forked-241k0?file=/src/App.jsx

**Comment by CodyJasonBennett** [comment]
I'm not able to recreate this locally. Do you still see this on your end?
